
sudo: required

language: java

services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - docker login -e=harsh.k.arora@gmail.com -u=harshkarora -p=Pranshi@03
  - echo "Docker Hub credentials are working"
  - docker build -t build-springxd-base .

script:
  - docker ps -a
