sudo: required

language: java

services:
  - docker

before_install:
  - cd systemlogic/RestApp
  - mvn clean install
  - echo "Testing Docker Hub credentials"
  - sudo docker login -u=harshkarora -p=Pranshi@03
  - echo "Docker Hub credentials are working"
  - docker build -t build-springxd-base .

script:
  - docker ps -a
