sudo: required

language: java

cache:
  timeout: 180
  directories:
  - /home/travis/.m2

services:
  - docker

before_install:
  - pwd
  - mvn clean install
  - echo "Testing Docker Hub credentials"
  - sudo docker login -u=harshkarora -p=$password
  - echo "Docker Hub credentials are working"
  - docker pull python:2.7-slim-jessie

script:
  - docker ps -a
